name: prettier

runs:
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install
        shell: bash
        run: yarn --frozen-lockfile
    - run: yarn prettier -w index.js
