name: sandbox
on: [push]
jobs:
  run-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
  create-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: date > foo.txt
      - name: Create New Branch and Commit
        run: |
          git checkout -b new-branch
          git add .
          git commit -m 'new commit from github actions'
      - name: Create release pr
        run: |
          gh pr create -B main -t "Pull Request From Github Actions" -b ""