name: sandbox
on: [push]
jobs:
  run-checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
  create-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update_foo_txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Pull Request from Github Actions!"
          body: |
            this is body
          commit-message: this is commit message
          branch: "bot/foo-${{ github.sha }}"
          base: master
          delete-branch: true